version: "3"
services:
  web:
    restart: always
    build: .
    links:
      - redis
    ports:
      - "127.0.0.1:1443:1443"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
      - EXPIRE_SECONDS=604800
      - BASE_URL=https://send.tommyang.org
  redis:
    restart: always
    image: redis:alpine
