version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "127.0.0.1:1443:1443"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
  redis:
    image: redis:alpine
